apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo
  annotations:
    github.com/project-slug: jondrusek/interview-exercises
spec:
  type: other
  lifecycle: unknown
  owner: devsec-users
