apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-kms-secrets
  namespace: default
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/interview-project/secrets/my-api-secret/versions/1"
        path: "api-secret.txt" # The filename the secret will have in the volume
      - resourceName: "projects/interview-project/secrets/another-secret/versions/latest"
        path: "another-secret.txt"
